### ISSUE TITLE
Fixing CSS cursor property

### ISSUE THREAD

**Issue by uddiptojana10** [akash-melkeri/studygram#14]
https://github.com/akash-melkeri/studygram/assets/117717963/7ff38406-d2be-446b-b5da-3a1d55d00f97

Cursor component can be fixed while selecting specific components. 
##You can assign me this under the Hacktoberfest Tag.

**Comment by akash-melkeri** [comment]
I have linked branch - 14 with this issue. You can checkout to the branch. After you have finished with changes raise a PR.
