### ISSUE TITLE
Fix: Styles on Button Pointer 

### ISSUE THREAD

**Issue by Surya-V-28** [akash-melkeri/studygram#15]
Bug : To follow the best UI /UX  design

Making the cursor to a pointer when hovering over a any clickable element is generally considered good UX practice. 

It provides a visual indication to the user that the element is interactive and can be clicked.

please assign this issues under  hacktober fest , 

I will make the PR , before merging please assign it to the hacktoberfest

**Comment by Surya-V-28** [comment]
please assign this to me.

**Comment by akash-melkeri** [comment]
Issue 14 is solving the same thing. you can try something else.
